import sys
import os
from pathlib import Path

# Add backend root to sys.path
backend_dir = Path(__file__).resolve().parent.parent
if str(backend_dir) not in sys.path:
    sys.path.insert(0, str(backend_dir))

from datetime import datetime, timedelta, timezone
from sqlalchemy.orm import Session
from app.core.database import SessionLocal, Base, engine
from app.models.product import Product
from app.models.mandate import Mandate

SEED_PRODUCTS = [
    {
        "id": "tea_001",
        "name": "Teddy Bear's Choice Fruit Tea",
        "brand": "Jenier World of Teas",
        "description": "A deliciously sweet, ruby-red infusion of dried elderberries, ripe blackcurrants, hibiscus petals, and blueberries. Naturally caffeine-free, packed with antioxidants, and irresistible hot or over ice.",
        "category": "Fruit & Herbal",
        "product_type": "Fruit Infusion",
        "price": 990,
        "cost_price": 450,
        "stock": 45,
        "rating": 4.9,
        "sales_count": 520,
        "views": 3410,
        "conversion_rate": 0.152,
        "color": "Ruby Red",
        "sizes_or_capacity": "50g Loose,100g Pouch,15 Pyramids,50 Pyramids",
        "specification": "100% Caffeine Free",
        "profit_per_unit": 540,
        "estimated_revenue": 514800,
        "estimated_profit": 280800,
        "stock_status": "in_stock",
        "attributes": {
            "brand": "Jenier World of Teas",
            "type": "Fruit Infusion",
            "badge": "BEST BUY",
            "badge_color": "green",
            "origin": "Black Forest, Germany",
            "caffeine_level": "None (0mg)",
            "steeping_temp": "100°C",
            "steeping_time": "5 - 8 mins",
            "ingredients": ["Elderberries", "Blackcurrants", "Hibiscus Petals", "Blueberries", "Natural Fruit Flavours"],
            "image_url": "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=600&auto=format&fit=crop&q=80",
            "packaging_options": [
                {"label": "50g Loose Leaf", "price": 9.90, "sku": "TB-50G"},
                {"label": "100g Pouch", "price": 16.90, "sku": "TB-100G"},
                {"label": "15 Biodegradable Pyramids", "price": 11.50, "sku": "TB-15P"},
                {"label": "50 Biodegradable Pyramids", "price": 29.90, "sku": "TB-50P"}
            ]
        }
    },
    {
        "id": "tea_002",
        "name": "Zesty Lemon Rooibos Tea",
        "brand": "Jenier World of Teas",
        "description": "Premium organic South African red bush rooibos blended with sun-ripened Mediterranean lemon peel, fragrant lemongrass, and golden calendula petals. Bright, aromatic, and deeply soothing.",
        "category": "Rooibos",
        "product_type": "Herbal Infusion",
        "price": 840,
        "cost_price": 380,
        "stock": 38,
        "rating": 4.8,
        "sales_count": 480,
        "views": 2950,
        "conversion_rate": 0.162,
        "color": "Amber Gold",
        "sizes_or_capacity": "50g Loose,100g Pouch,15 Pyramids,50 Pyramids",
        "specification": "Naturally Caffeine Free",
        "profit_per_unit": 460,
        "estimated_revenue": 403200,
        "estimated_profit": 220800,
        "stock_status": "in_stock",
        "attributes": {
            "brand": "Jenier World of Teas",
            "type": "Herbal Infusion",
            "badge": "BEST BUY",
            "badge_color": "green",
            "origin": "Cederberg Mountains, South Africa",
            "caffeine_level": "None (0mg)",
            "steeping_temp": "100°C",
            "steeping_time": "4 - 6 mins",
            "ingredients": ["Organic Rooibos", "Lemon Peel", "Lemongrass", "Calendula Petals", "Natural Lemon Essence"],
            "image_url": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80",
            "packaging_options": [
                {"label": "50g Loose Leaf", "price": 8.40, "sku": "ZL-50G"},
                {"label": "100g Pouch", "price": 14.90, "sku": "ZL-100G"},
                {"label": "15 Biodegradable Pyramids", "price": 9.90, "sku": "ZL-15P"},
                {"label": "50 Biodegradable Pyramids", "price": 26.50, "sku": "ZL-50P"}
            ]
        }
    },
    {
        "id": "tea_003",
        "name": "Yorkshire Harrogate Everyday Tea",
        "brand": "Jenier World of Teas",
        "description": "An authentic, robust British breakfast blend of rich Assam and brisk high-grown Kenyan black teas. Designed to deliver an invigorating amber cup with exceptional strength and malty depth.",
        "category": "Black Tea",
        "product_type": "Black Tea",
        "price": 840,
        "cost_price": 360,
        "stock": 60,
        "rating": 4.9,
        "sales_count": 680,
        "views": 4120,
        "conversion_rate": 0.165,
        "color": "Deep Mahogany",
        "sizes_or_capacity": "50g Loose,100g Pouch,15 Pyramids,50 Pyramids",
        "specification": "High Caffeine (45mg)",
        "profit_per_unit": 480,
        "estimated_revenue": 571200,
        "estimated_profit": 326400,
        "stock_status": "in_stock",
        "attributes": {
            "brand": "Jenier World of Teas",
            "type": "Black Tea",
            "badge": "NEW",
            "badge_color": "orange",
            "origin": "Assam, India & Kericho, Kenya",
            "caffeine_level": "High (45mg)",
            "steeping_temp": "100°C",
            "steeping_time": "3 - 5 mins",
            "ingredients": ["100% Pure Fine Cut Black Teas"],
            "image_url": "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=600&auto=format&fit=crop&q=80",
            "packaging_options": [
                {"label": "50g Loose Leaf", "price": 8.40, "sku": "YH-50G"},
                {"label": "100g Pouch", "price": 14.50, "sku": "YH-100G"},
                {"label": "15 Biodegradable Pyramids", "price": 9.90, "sku": "YH-15P"},
                {"label": "50 Biodegradable Pyramids", "price": 25.90, "sku": "YH-50P"}
            ]
        }
    },
    {
        "id": "tea_004",
        "name": "Earl Grey Supreme Biodegradable Pyramids",
        "brand": "Jenier World of Teas",
        "description": "Selected whole-leaf Ceylon OP black tea delicately scented with cold-pressed Italian bergamot essential oil and adorned with blue cornflower petals.",
        "category": "Black Tea",
        "product_type": "Flavoured Black",
        "price": 1150,
        "cost_price": 500,
        "stock": 50,
        "rating": 4.9,
        "sales_count": 430,
        "views": 3100,
        "conversion_rate": 0.138,
        "color": "Amber Russet",
        "sizes_or_capacity": "15 Pyramids,50 Pyramids,100g Loose",
        "specification": "Medium Caffeine (35mg)",
        "profit_per_unit": 650,
        "estimated_revenue": 494500,
        "estimated_profit": 279500,
        "stock_status": "in_stock",
        "attributes": {
            "brand": "Jenier World of Teas",
            "type": "Flavoured Black",
            "badge": "BEST BUY",
            "badge_color": "green",
            "origin": "Dimbula, Sri Lanka & Calabria, Italy",
            "caffeine_level": "Medium (35mg)",
            "steeping_temp": "95°C",
            "steeping_time": "3 - 4 mins",
            "ingredients": ["Ceylon Black Tea", "Natural Cold-Pressed Bergamot Oil", "Cornflower Petals"],
            "image_url": "https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=600&auto=format&fit=crop&q=80",
            "packaging_options": [
                {"label": "15 Biodegradable Pyramids", "price": 11.50, "sku": "EG-15P"},
                {"label": "50 Biodegradable Pyramids", "price": 31.00, "sku": "EG-50P"},
                {"label": "100g Pouch", "price": 18.00, "sku": "EG-100G"}
            ]
        }
    },
    {
        "id": "tea_005",
        "name": "Japanese Sencha Organic Green Tea",
        "brand": "Jenier World of Teas",
        "description": "Tender spring first-flush steamed green tea leaves from organic gardens in Kagoshima. Clean jade liquor with rich umami and refreshing vegetal sweetness.",
        "category": "Green & White",
        "product_type": "Green Tea",
        "price": 1290,
        "cost_price": 600,
        "stock": 32,
        "rating": 4.8,
        "sales_count": 310,
        "views": 2400,
        "conversion_rate": 0.129,
        "color": "Vibrant Jade",
        "sizes_or_capacity": "50g Loose,100g Pouch,15 Pyramids",
        "specification": "Low Caffeine (20mg)",
        "profit_per_unit": 690,
        "estimated_revenue": 399900,
        "estimated_profit": 213900,
        "stock_status": "in_stock",
        "attributes": {
            "brand": "Jenier World of Teas",
            "type": "Green Tea",
            "badge": "ORGANIC",
            "badge_color": "emerald",
            "origin": "Kagoshima, Japan",
            "caffeine_level": "Low (20mg)",
            "steeping_temp": "80°C",
            "steeping_time": "2 - 3 mins",
            "ingredients": ["100% Certified Organic Japanese Green Tea"],
            "image_url": "https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?w=600&auto=format&fit=crop&q=80",
            "packaging_options": [
                {"label": "50g Loose Leaf", "price": 12.90, "sku": "JS-50G"},
                {"label": "100g Pouch", "price": 22.50, "sku": "JS-100G"},
                {"label": "15 Biodegradable Pyramids", "price": 13.90, "sku": "JS-15P"}
            ]
        }
    },
    {
        "id": "tea_006",
        "name": "Artisan Borosilicate Glass Teapot (800ml)",
        "brand": "Jenier World of Teas",
        "description": "Ultra-clear thermal shock resistant borosilicate glass teapot complete with an ultra-fine stainless steel infuser basket. Ideal for watching pyramid teabags and loose leaves unfurl.",
        "category": "Teaware & Gifts",
        "product_type": "Teaware",
        "price": 2490,
        "cost_price": 1100,
        "stock": 18,
        "rating": 4.9,
        "sales_count": 210,
        "views": 1980,
        "conversion_rate": 0.106,
        "color": "Clear Glass / Stainless Steel",
        "sizes_or_capacity": "800ml Capacity",
        "specification": "Borosilicate Heat Resistant",
        "profit_per_unit": 1390,
        "estimated_revenue": 522900,
        "estimated_profit": 291900,
        "stock_status": "in_stock",
        "attributes": {
            "brand": "Jenier World of Teas",
            "type": "Teaware",
            "badge": "NEW",
            "badge_color": "orange",
            "origin": "Artisan Glassworks",
            "caffeine_level": "N/A",
            "steeping_temp": "Up to 150°C",
            "steeping_time": "N/A",
            "ingredients": ["Borosilicate Glass", "304 Food-Grade Stainless Steel"],
            "image_url": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&auto=format&fit=crop&q=80",
            "packaging_options": [
                {"label": "800ml Glass Teapot + Infuser", "price": 24.90, "sku": "TP-800ML"}
            ]
        }
    },
    {
        "id": "prod_001",
        "name": "Sprint Runner",
        "brand": "Velocity",
        "description": "High-performance lightweight running shoe with breathable mesh upper.",
        "category": "Footwear",
        "product_type": "Running",
        "price": 1299,
        "cost_price": 799,
        "stock": 15,
        "rating": 4.5,
        "sales_count": 245,
        "views": 1820,
        "conversion_rate": 0.134,
        "color": "Neon Lime / Black",
        "sizes_or_capacity": "7,8,9,10",
        "specification": "220g",
        "profit_per_unit": 500,
        "estimated_revenue": 318255,
        "estimated_profit": 122500,
        "stock_status": "in_stock",
        "attributes": {"brand": "Velocity", "type": "Running", "sizes": ["7", "8", "9", "10"], "color": "Neon Lime / Black", "weight": "220g"}
    },
    {
        "id": "prod_002",
        "name": "Premium Runner",
        "brand": "AeroStride",
        "description": "Carbon-plated marathon running shoe with high energy return.",
        "category": "Footwear",
        "product_type": "Running",
        "price": 1799,
        "cost_price": 1120,
        "stock": 8,
        "rating": 4.7,
        "sales_count": 198,
        "views": 1540,
        "conversion_rate": 0.129,
        "color": "Carbon Black / Gold",
        "sizes_or_capacity": "8,9,10,11",
        "specification": "195g",
        "profit_per_unit": 679,
        "estimated_revenue": 356202,
        "estimated_profit": 134442,
        "stock_status": "in_stock",
        "attributes": {"brand": "AeroStride", "type": "Running", "sizes": ["8", "9", "10", "11"], "color": "Carbon Black / Gold", "weight": "195g"}
    },
    {
        "id": "prod_003",
        "name": "Trail Blaze Pro",
        "brand": "TrailForce",
        "description": "Rugged all-terrain trail shoe with high-traction outsole.",
        "category": "Footwear",
        "product_type": "Trail",
        "price": 2499,
        "cost_price": 1550,
        "stock": 6,
        "rating": 4.6,
        "sales_count": 121,
        "views": 980,
        "conversion_rate": 0.123,
        "color": "Olive Green",
        "sizes_or_capacity": "8,9,10",
        "specification": "310g",
        "profit_per_unit": 949,
        "estimated_revenue": 302379,
        "estimated_profit": 114829,
        "stock_status": "low_stock",
        "attributes": {"brand": "TrailForce", "type": "Trail", "sizes": ["8", "9", "10"], "color": "Olive Green", "weight": "310g"}
    },
    {
        "id": "prod_004",
        "name": "Urban Sneaker Lite",
        "brand": "UrbanFlex",
        "description": "Comfortable everyday sneaker with memory foam cushioning.",
        "category": "Footwear",
        "product_type": "Lifestyle",
        "price": 999,
        "cost_price": 590,
        "stock": 25,
        "rating": 4.3,
        "sales_count": 310,
        "views": 2680,
        "conversion_rate": 0.116,
        "color": "Cloud White",
        "sizes_or_capacity": "7,8,9,10",
        "specification": "260g",
        "profit_per_unit": 409,
        "estimated_revenue": 309690,
        "estimated_profit": 126790,
        "stock_status": "in_stock",
        "attributes": {"brand": "UrbanFlex", "type": "Lifestyle", "sizes": ["7", "8", "9", "10"], "color": "Cloud White", "weight": "260g"}
    },
    {
        "id": "prod_005",
        "name": "SonicPulse Wireless Earbuds",
        "brand": "SonicPulse",
        "description": "Sweatproof sports earbuds with deep bass and extended battery life.",
        "category": "Electronics",
        "product_type": "Audio",
        "price": 1499,
        "cost_price": 900,
        "stock": 12,
        "rating": 4.4,
        "sales_count": 276,
        "views": 2250,
        "conversion_rate": 0.123,
        "color": "Matte Black",
        "sizes_or_capacity": "Universal",
        "specification": "32h",
        "profit_per_unit": 599,
        "estimated_revenue": 413724,
        "estimated_profit": 165324,
        "stock_status": "in_stock",
        "attributes": {"brand": "SonicPulse", "type": "Audio", "battery": "32h", "color": "Matte Black"}
    },
    {
        "id": "prod_006",
        "name": "ProGrip Resistance Bands",
        "brand": "ProGrip",
        "description": "Five-pack heavy-duty resistance loop bands for home and gym training.",
        "category": "Fitness",
        "product_type": "Strength",
        "price": 699,
        "cost_price": 350,
        "stock": 30,
        "rating": 4.6,
        "sales_count": 420,
        "views": 3120,
        "conversion_rate": 0.135,
        "color": "Multicolor",
        "sizes_or_capacity": "X-Light,Light,Medium,Heavy,X-Heavy",
        "specification": "Natural Latex",
        "profit_per_unit": 349,
        "estimated_revenue": 293580,
        "estimated_profit": 146580,
        "stock_status": "in_stock",
        "attributes": {"brand": "ProGrip", "type": "Strength", "levels": ["X-Light", "Light", "Medium", "Heavy", "X-Heavy"], "material": "Natural Latex"}
    },
    {
        "id": "prod_007",
        "name": "Thermal Hydration Flask",
        "brand": "HydraCore",
        "description": "Double-wall vacuum insulated stainless steel sports bottle.",
        "category": "Accessories",
        "product_type": "Hydration",
        "price": 499,
        "cost_price": 220,
        "stock": 40,
        "rating": 4.5,
        "sales_count": 512,
        "views": 3890,
        "conversion_rate": 0.132,
        "color": "Steel Blue",
        "sizes_or_capacity": "750ml",
        "specification": "24h Cold / 12h Hot",
        "profit_per_unit": 279,
        "estimated_revenue": 255488,
        "estimated_profit": 142848,
        "stock_status": "in_stock",
        "attributes": {"brand": "HydraCore", "type": "Hydration", "capacity": "750ml", "insulation": "24h Cold / 12h Hot", "color": "Steel Blue"}
    },
    {
        "id": "prod_008",
        "name": "AeroFit Performance Tee",
        "brand": "AeroFit",
        "description": "Ultra-light moisture-wicking athletic t-shirt with anti-odor fabric.",
        "category": "Clothing",
        "product_type": "Performance",
        "price": 899,
        "cost_price": 430,
        "stock": 20,
        "rating": 4.4,
        "sales_count": 355,
        "views": 2940,
        "conversion_rate": 0.121,
        "color": "Charcoal Grey",
        "sizes_or_capacity": "S,M,L,XL",
        "specification": "DryFit Micro-Poly",
        "profit_per_unit": 469,
        "estimated_revenue": 319145,
        "estimated_profit": 166495,
        "stock_status": "in_stock",
        "attributes": {"brand": "AeroFit", "type": "Performance", "sizes": ["S", "M", "L", "XL"], "fabric": "DryFit Micro-Poly", "color": "Charcoal Grey"}
    },
    {
        "id": "prod_009",
        "name": "Apex Smart Fitness Tracker",
        "brand": "Apex",
        "description": "Fitness tracker with AMOLED display, heart rate and SpO2 monitoring.",
        "category": "Electronics",
        "product_type": "Wearables",
        "price": 2199,
        "cost_price": 1350,
        "stock": 7,
        "rating": 4.2,
        "sales_count": 143,
        "views": 1710,
        "conversion_rate": 0.084,
        "color": "Midnight Black",
        "sizes_or_capacity": "Universal",
        "specification": "1.47-inch AMOLED",
        "profit_per_unit": 849,
        "estimated_revenue": 314457,
        "estimated_profit": 121407,
        "stock_status": "low_stock",
        "attributes": {"brand": "Apex", "type": "Wearables", "display": "1.47-inch AMOLED", "sensors": ["HeartRate", "SpO2", "Sleep"], "color": "Midnight Black"}
    },
    {
        "id": "prod_010",
        "name": "Phantom Sprint Elite",
        "brand": "Phantom",
        "description": "Special-edition lightweight track shoe for sprint training.",
        "category": "Footwear",
        "product_type": "Track",
        "price": 1450,
        "cost_price": 850,
        "stock": 0,
        "rating": 4.8,
        "sales_count": 312,
        "views": 2100,
        "conversion_rate": 0.148,
        "color": "Electric Blue",
        "sizes_or_capacity": "9,10",
        "specification": "190g",
        "profit_per_unit": 600,
        "estimated_revenue": 452400,
        "estimated_profit": 187200,
        "stock_status": "out_of_stock",
        "attributes": {"brand": "Phantom", "type": "Track", "sizes": ["9", "10"], "color": "Electric Blue", "weight": "190g"}
    },
    {
        "id": "prod_011",
        "name": "Anti-Blister Running Socks",
        "brand": "Endura",
        "description": "Compression running socks designed to reduce friction and blistering.",
        "category": "Footwear",
        "product_type": "Accessory",
        "price": 149,
        "cost_price": 65,
        "stock": 50,
        "rating": 4.5,
        "sales_count": 690,
        "views": 4820,
        "conversion_rate": 0.118,
        "color": "Black",
        "sizes_or_capacity": "M,L",
        "specification": "Merino-CoolMax Blend",
        "profit_per_unit": 84,
        "estimated_revenue": 102810,
        "estimated_profit": 57960,
        "stock_status": "in_stock",
        "attributes": {"brand": "Endura", "type": "Accessory", "sizes": ["M", "L"], "material": "Merino-CoolMax Blend", "color": "Black"}
    },
    {
        "id": "prod_012",
        "name": "Cushioned Gel Insoles",
        "brand": "StrideCare",
        "description": "Shock-absorbing dual-gel replacement insoles for running shoes.",
        "category": "Footwear",
        "product_type": "Accessory",
        "price": 199,
        "cost_price": 90,
        "stock": 35,
        "rating": 4.4,
        "sales_count": 575,
        "views": 4210,
        "conversion_rate": 0.106,
        "color": "Blue",
        "sizes_or_capacity": "Universal Trim-to-Fit",
        "specification": "High Support",
        "profit_per_unit": 109,
        "estimated_revenue": 114425,
        "estimated_profit": 62675,
        "stock_status": "in_stock",
        "attributes": {"brand": "StrideCare", "type": "Accessory", "sizes": ["Universal Trim-to-Fit"], "specification": "High Support", "color": "Blue"}
    },
    {
        "id": "prod_013",
        "name": "Endurance Runner X",
        "brand": "Velocity",
        "description": "Responsive road-running shoe designed for long-distance comfort.",
        "category": "Footwear",
        "product_type": "Running",
        "price": 1599,
        "cost_price": 960,
        "stock": 18,
        "rating": 4.6,
        "sales_count": 288,
        "views": 2190,
        "conversion_rate": 0.132,
        "color": "Royal Blue / White",
        "sizes_or_capacity": "7,8,9,10,11",
        "specification": "225g",
        "profit_per_unit": 639,
        "estimated_revenue": 460512,
        "estimated_profit": 184032,
        "stock_status": "in_stock",
        "attributes": {"brand": "Velocity", "type": "Running", "sizes": ["7", "8", "9", "10", "11"], "color": "Royal Blue / White", "weight": "225g"}
    },
    {
        "id": "prod_014",
        "name": "Daily Walk Comfort",
        "brand": "UrbanFlex",
        "description": "Soft-cushioned walking shoe for daily commuting and casual use.",
        "category": "Footwear",
        "product_type": "Walking",
        "price": 1199,
        "cost_price": 680,
        "stock": 22,
        "rating": 4.3,
        "sales_count": 260,
        "views": 2370,
        "conversion_rate": 0.11,
        "color": "Grey",
        "sizes_or_capacity": "7,8,9,10",
        "specification": "275g",
        "profit_per_unit": 519,
        "estimated_revenue": 311740,
        "estimated_profit": 134940,
        "stock_status": "in_stock",
        "attributes": {"brand": "UrbanFlex", "type": "Walking", "sizes": ["7", "8", "9", "10"], "color": "Grey", "weight": "275g"}
    },
    {
        "id": "prod_015",
        "name": "SpeedCore Track",
        "brand": "Phantom",
        "description": "Lightweight sprint shoe built for track workouts and speed sessions.",
        "category": "Footwear",
        "product_type": "Track",
        "price": 1399,
        "cost_price": 820,
        "stock": 11,
        "rating": 4.7,
        "sales_count": 205,
        "views": 1680,
        "conversion_rate": 0.122,
        "color": "Red / Black",
        "sizes_or_capacity": "8,9,10",
        "specification": "185g",
        "profit_per_unit": 579,
        "estimated_revenue": 286795,
        "estimated_profit": 118695,
        "stock_status": "in_stock",
        "attributes": {"brand": "Phantom", "type": "Track", "sizes": ["8", "9", "10"], "color": "Red / Black", "weight": "185g"}
    },
    {
        "id": "prod_016",
        "name": "MountainGrip Trail",
        "brand": "TrailForce",
        "description": "Durable trail shoe with aggressive grip for uneven terrain.",
        "category": "Footwear",
        "product_type": "Trail",
        "price": 2299,
        "cost_price": 1410,
        "stock": 9,
        "rating": 4.5,
        "sales_count": 156,
        "views": 1320,
        "conversion_rate": 0.118,
        "color": "Forest Green",
        "sizes_or_capacity": "8,9,10,11",
        "specification": "325g",
        "profit_per_unit": 889,
        "estimated_revenue": 358644,
        "estimated_profit": 138684,
        "stock_status": "in_stock",
        "attributes": {"brand": "TrailForce", "type": "Trail", "sizes": ["8", "9", "10", "11"], "color": "Forest Green", "weight": "325g"}
    },
    {
        "id": "prod_017",
        "name": "FlexMove Training Shoe",
        "brand": "AeroStride",
        "description": "Versatile cross-training shoe for gym workouts and functional training.",
        "category": "Footwear",
        "product_type": "Training",
        "price": 1699,
        "cost_price": 980,
        "stock": 16,
        "rating": 4.4,
        "sales_count": 214,
        "views": 1890,
        "conversion_rate": 0.113,
        "color": "Black / Orange",
        "sizes_or_capacity": "7,8,9,10,11",
        "specification": "245g",
        "profit_per_unit": 719,
        "estimated_revenue": 363586,
        "estimated_profit": 153866,
        "stock_status": "in_stock",
        "attributes": {"brand": "AeroStride", "type": "Training", "sizes": ["7", "8", "9", "10", "11"], "color": "Black / Orange", "weight": "245g"}
    },
    {
        "id": "prod_018",
        "name": "CloudStep Recovery Shoe",
        "brand": "StrideCare",
        "description": "Soft recovery footwear with supportive cushioning after training.",
        "category": "Footwear",
        "product_type": "Recovery",
        "price": 1299,
        "cost_price": 720,
        "stock": 19,
        "rating": 4.5,
        "sales_count": 177,
        "views": 1740,
        "conversion_rate": 0.102,
        "color": "Sand White",
        "sizes_or_capacity": "7,8,9,10",
        "specification": "285g",
        "profit_per_unit": 579,
        "estimated_revenue": 229923,
        "estimated_profit": 102483,
        "stock_status": "in_stock",
        "attributes": {"brand": "StrideCare", "type": "Recovery", "sizes": ["7", "8", "9", "10"], "color": "Sand White", "weight": "285g"}
    },
    {
        "id": "prod_019",
        "name": "BassBeat Sport Buds",
        "brand": "SonicPulse",
        "description": "Compact wireless sports earbuds with secure-fit ear tips.",
        "category": "Electronics",
        "product_type": "Audio",
        "price": 1199,
        "cost_price": 690,
        "stock": 17,
        "rating": 4.3,
        "sales_count": 231,
        "views": 2010,
        "conversion_rate": 0.115,
        "color": "Black / Red",
        "sizes_or_capacity": "Universal",
        "specification": "24h",
        "profit_per_unit": 509,
        "estimated_revenue": 276969,
        "estimated_profit": 117579,
        "stock_status": "in_stock",
        "attributes": {"brand": "SonicPulse", "type": "Audio", "battery": "24h", "color": "Black / Red"}
    },
    {
        "id": "prod_020",
        "name": "ChargeGo Power Bank",
        "brand": "VoltEdge",
        "description": "Portable fast-charging power bank for phones and fitness devices.",
        "category": "Electronics",
        "product_type": "Accessories",
        "price": 899,
        "cost_price": 520,
        "stock": 24,
        "rating": 4.4,
        "sales_count": 301,
        "views": 2510,
        "conversion_rate": 0.12,
        "color": "Dark Grey",
        "sizes_or_capacity": "10000mAh",
        "specification": "22.5W",
        "profit_per_unit": 379,
        "estimated_revenue": 270599,
        "estimated_profit": 114079,
        "stock_status": "in_stock",
        "attributes": {"brand": "VoltEdge", "type": "Accessories", "capacity": "10000mAh", "power": "22.5W", "color": "Dark Grey"}
    },
    {
        "id": "prod_021",
        "name": "PulseWatch Active",
        "brand": "Apex",
        "description": "Smart fitness watch with workout tracking, sleep monitoring and notifications.",
        "category": "Electronics",
        "product_type": "Wearables",
        "price": 2499,
        "cost_price": 1580,
        "stock": 5,
        "rating": 4.1,
        "sales_count": 119,
        "views": 1460,
        "conversion_rate": 0.081,
        "color": "Graphite",
        "sizes_or_capacity": "Universal",
        "specification": "1.6-inch AMOLED",
        "profit_per_unit": 919,
        "estimated_revenue": 297381,
        "estimated_profit": 109361,
        "stock_status": "low_stock",
        "attributes": {"brand": "Apex", "type": "Wearables", "display": "1.6-inch AMOLED", "color": "Graphite"}
    },
    {
        "id": "prod_022",
        "name": "CoreFlex Yoga Mat",
        "brand": "CoreFlex",
        "description": "Non-slip exercise mat for yoga, stretching and mobility sessions.",
        "category": "Fitness",
        "product_type": "Yoga",
        "price": 799,
        "cost_price": 390,
        "stock": 28,
        "rating": 4.6,
        "sales_count": 382,
        "views": 2860,
        "conversion_rate": 0.129,
        "color": "Purple",
        "sizes_or_capacity": "183 x 61 cm",
        "specification": "6mm",
        "profit_per_unit": 409,
        "estimated_revenue": 305218,
        "estimated_profit": 156238,
        "stock_status": "in_stock",
        "attributes": {"brand": "CoreFlex", "type": "Yoga", "dimensions": "183 x 61 cm", "thickness": "6mm", "color": "Purple"}
    },
    {
        "id": "prod_023",
        "name": "SpeedRope Pro",
        "brand": "ProGrip",
        "description": "Adjustable speed rope designed for cardio and conditioning workouts.",
        "category": "Fitness",
        "product_type": "Cardio",
        "price": 599,
        "cost_price": 280,
        "stock": 33,
        "rating": 4.5,
        "sales_count": 446,
        "views": 3290,
        "conversion_rate": 0.137,
        "color": "Black",
        "sizes_or_capacity": "Adjustable",
        "specification": "2.8m",
        "profit_per_unit": 319,
        "estimated_revenue": 267154,
        "estimated_profit": 142274,
        "stock_status": "in_stock",
        "attributes": {"brand": "ProGrip", "type": "Cardio", "length": "2.8m", "color": "Black"}
    },
    {
        "id": "prod_024",
        "name": "IronCore Adjustable Dumbbells",
        "brand": "IronCore",
        "description": "Compact adjustable dumbbell set for home strength training.",
        "category": "Fitness",
        "product_type": "Strength",
        "price": 2999,
        "cost_price": 1900,
        "stock": 4,
        "rating": 4.7,
        "sales_count": 97,
        "views": 1120,
        "conversion_rate": 0.087,
        "color": "Black",
        "sizes_or_capacity": "Adjustable",
        "specification": "Up to 20kg",
        "profit_per_unit": 1099,
        "estimated_revenue": 290903,
        "estimated_profit": 106603,
        "stock_status": "low_stock",
        "attributes": {"brand": "IronCore", "type": "Strength", "weight": "Up to 20kg", "color": "Black"}
    },
    {
        "id": "prod_025",
        "name": "FlexDry Training Shorts",
        "brand": "AeroFit",
        "description": "Lightweight quick-dry shorts for running, gym and training.",
        "category": "Clothing",
        "product_type": "Performance",
        "price": 699,
        "cost_price": 320,
        "stock": 26,
        "rating": 4.4,
        "sales_count": 332,
        "views": 2750,
        "conversion_rate": 0.121,
        "color": "Navy Blue",
        "sizes_or_capacity": "S,M,L,XL",
        "specification": "Polyester Stretch",
        "profit_per_unit": 379,
        "estimated_revenue": 232068,
        "estimated_profit": 125828,
        "stock_status": "in_stock",
        "attributes": {"brand": "AeroFit", "type": "Performance", "sizes": ["S", "M", "L", "XL"], "material": "Polyester Stretch", "color": "Navy Blue"}
    },
    {
        "id": "prod_026",
        "name": "RunShield Lightweight Jacket",
        "brand": "AeroFit",
        "description": "Lightweight wind-resistant training jacket for outdoor workouts.",
        "category": "Clothing",
        "product_type": "Outerwear",
        "price": 1499,
        "cost_price": 780,
        "stock": 13,
        "rating": 4.5,
        "sales_count": 189,
        "views": 1620,
        "conversion_rate": 0.117,
        "color": "Black",
        "sizes_or_capacity": "S,M,L,XL",
        "specification": "WindShell",
        "profit_per_unit": 719,
        "estimated_revenue": 283311,
        "estimated_profit": 135891,
        "stock_status": "in_stock",
        "attributes": {"brand": "AeroFit", "type": "Outerwear", "sizes": ["S", "M", "L", "XL"], "material": "WindShell", "color": "Black"}
    },
    {
        "id": "prod_027",
        "name": "SprintCap Performance Cap",
        "brand": "AeroFit",
        "description": "Breathable quick-dry sports cap for running and outdoor training.",
        "category": "Accessories",
        "product_type": "Headwear",
        "price": 399,
        "cost_price": 160,
        "stock": 38,
        "rating": 4.3,
        "sales_count": 511,
        "views": 3610,
        "conversion_rate": 0.141,
        "color": "Black",
        "sizes_or_capacity": "Adjustable",
        "specification": "Polyester Mesh",
        "profit_per_unit": 239,
        "estimated_revenue": 203889,
        "estimated_profit": 122129,
        "stock_status": "in_stock",
        "attributes": {"brand": "AeroFit", "type": "Headwear", "material": "Polyester Mesh", "color": "Black"}
    },
    {
        "id": "prod_028",
        "name": "Athlete Pro Gym Bag",
        "brand": "CoreFlex",
        "description": "Spacious training bag with separate shoe and accessory compartments.",
        "category": "Accessories",
        "product_type": "Bags",
        "price": 1299,
        "cost_price": 650,
        "stock": 14,
        "rating": 4.6,
        "sales_count": 204,
        "views": 1810,
        "conversion_rate": 0.113,
        "color": "Charcoal",
        "sizes_or_capacity": "35L",
        "specification": "Water-resistant Polyester",
        "profit_per_unit": 649,
        "estimated_revenue": 264996,
        "estimated_profit": 132396,
        "stock_status": "in_stock",
        "attributes": {"brand": "CoreFlex", "type": "Bags", "capacity": "35L", "material": "Water-resistant Polyester", "color": "Charcoal"}
    },
    {
        "id": "prod_029",
        "name": "CoolTowel Sports Towel",
        "brand": "HydraCore",
        "description": "Quick-drying cooling towel for workouts and outdoor activities.",
        "category": "Accessories",
        "product_type": "Towel",
        "price": 299,
        "cost_price": 120,
        "stock": 45,
        "rating": 4.4,
        "sales_count": 623,
        "views": 4150,
        "conversion_rate": 0.15,
        "color": "Blue",
        "sizes_or_capacity": "One Size",
        "specification": "Microfiber",
        "profit_per_unit": 179,
        "estimated_revenue": 186277,
        "estimated_profit": 111517,
        "stock_status": "in_stock",
        "attributes": {"brand": "HydraCore", "type": "Towel", "material": "Microfiber", "color": "Blue"}
    },
    {
        "id": "prod_030",
        "name": "Recovery Massage Ball",
        "brand": "CoreFlex",
        "description": "Compact massage ball for post-workout muscle recovery and mobility.",
        "category": "Fitness",
        "product_type": "Recovery",
        "price": 349,
        "cost_price": 150,
        "stock": 41,
        "rating": 4.5,
        "sales_count": 537,
        "views": 3900,
        "conversion_rate": 0.138,
        "color": "Green",
        "sizes_or_capacity": "One Size",
        "specification": "High-density EVA",
        "profit_per_unit": 199,
        "estimated_revenue": 187413,
        "estimated_profit": 106863,
        "stock_status": "in_stock",
        "attributes": {"brand": "CoreFlex", "type": "Recovery", "material": "High-density EVA", "color": "Green"}
    }
]

def seed_db():
    Base.metadata.create_all(bind=engine)
    db: Session = SessionLocal()
    try:
        # Seed Products
        for p_data in SEED_PRODUCTS:
            existing = db.query(Product).filter(Product.id == p_data["id"]).first()
            if not existing:
                product = Product(**p_data)
                db.add(product)
            else:
                # Update attributes / stock / price / metrics
                for k, v in p_data.items():
                    setattr(existing, k, v)
        
        # Seed Default Mandate
        demo_mandate = db.query(Mandate).filter(Mandate.id == "mandate_demo").first()
        allowed_cats = [
            "Footwear", "footwear", "Travel gear", "Office", "Electronics",
            "Fruit & Herbal", "Rooibos", "Black Tea", "Green & White", 
            "Teaware & Gifts", "Pyramid Teabags", "Tea", "Teas"
        ]
        if not demo_mandate:
            mandate = Mandate(
                id="mandate_demo",
                merchant_id="merchant_demo",
                max_amount=1500,
                allowed_categories=allowed_cats,
                max_items_per_order=1,
                expires_at=datetime.now(timezone.utc) + timedelta(days=180),
                status="active"
            )
            db.add(mandate)
        else:
            demo_mandate.max_amount = 1500
            demo_mandate.allowed_categories = allowed_cats
            demo_mandate.max_items_per_order = 1
            demo_mandate.status = "active"

        # Seed Travel Mandate (matches Figma UI specification)
        travel_mandate = db.query(Mandate).filter(Mandate.id == "mandate_travel").first()
        travel_cats = ["Travel gear", "Office", "Electronics", "Footwear"]
        if not travel_mandate:
            mandate = Mandate(
                id="mandate_travel",
                merchant_id="merchant_demo",
                max_amount=800,
                allowed_categories=travel_cats,
                max_items_per_order=4,
                expires_at=datetime.now(timezone.utc) + timedelta(days=2, hours=14, minutes=8),
                status="active"
            )
            db.add(mandate)
        else:
            travel_mandate.max_amount = 800
            travel_mandate.allowed_categories = travel_cats
            travel_mandate.max_items_per_order = 4
            travel_mandate.expires_at = datetime.now(timezone.utc) + timedelta(days=2, hours=14, minutes=8)
            travel_mandate.status = "active"

        db.commit()
        print(f"Database seeded successfully with {len(SEED_PRODUCTS)} products and demo mandate.")
    finally:
        db.close()

if __name__ == "__main__":
    seed_db()

